runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://npm.pkg.github.com"
        scope: "@kungfu-trader"

    - name: Setup Node.js registry scope
      if: ${{ inputs.publish-github-npm }}
      uses: actions/setup-node@v2
      with:
        registry-url: "https://npm.pkg.github.com"
        scope: "@${{github.repository_owner}}"

    - name: Bump Version
      uses: kungfu-trader/action-bump-version@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        action: "prebuild"

    - name: Configure AWS Crendentials (CI)
      if: ${{ inputs.publish-aws-ci }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-ci-region }}

    - name: Publish Prebuilt to AWS (CI)
      if: ${{ inputs.publish-aws-ci }}
      uses: kungfu-trader/action-publish-prebuilt@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        bucket-staging: ${{ inputs.bucket-staging-ci }}
        bucket-release: ${{ inputs.bucket-release-ci }}
        clean-release: ${{ inputs.clean-release-ci }}
        cloudfront-id: ${{ inputs.cloudfront-id-ci }}
        cloudfront-paths: ${{ inputs.cloudfront-paths-ci }}
        no-comment: 'true'

    - name: Configure AWS Crendentials (User)
      if: ${{ inputs.publish-aws-user }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-user-region }}

    - name: Publish Prebuilt to AWS (User)
      if: ${{ inputs.publish-aws-user }}
      uses: kungfu-trader/action-publish-prebuilt@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        bucket-staging: ${{ inputs.bucket-staging-user }}
        bucket-release: ${{ inputs.bucket-release-user }}
        clean-release: ${{ inputs.clean-release-user }}
        cloudfront-id: ${{ inputs.cloudfront-id-user }}
        cloudfront-paths: ${{ inputs.cloudfront-paths-user }}

    - name: Publish New Version To GitHub
      if: ${{ github.event.pull_request.merged && inputs.publish-github-npm }}
      uses: kungfu-trader/action-bump-version@v3
      with:
        token: ${{ secrets.GITHUB_PUSH_TOKEN }}
        action: "postbuild"

    - name: Setup NPM registry
      if: ${{ inputs.publish-npmjs }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Setup NPM registry for owner
      if: ${{ inputs.publish-npmjs }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        scope: "@${{github.repository_owner}}"

    - name: Publish to NPM Packages
      if: ${{ inputs.publish-npmjs }}
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUSH_TOKEN }}
