on:
    workflow_call:
      inputs:
        pull-request-title:
          type: string
          required: false
        repo:
          type: string
          default: ''
          required: false
        repo-includes:
          type: string
          default: ''
          required: false
      secrets:
        GITHUB_PUSH_TOKEN:
          required: true

jobs:
    batch-pull-request:
      runs-on: ubuntu-22.04
      steps:
        - name: update deps version
          uses: kungfu-trader/action-update-dependencies-version@dev/v1/v1.0
          continue-on-error: true
          with:
              token: ${{ secrets.GITHUB_PUSH_TOKEN }}
              repo: ${{ inputs.repo }}
              repo-includes: ${{ inputs.repo-includes }}

        - name: request batch pr
          uses: indiesdev/curl@v1.1
          continue-on-error: true
          with:
              url: https://api.github.com/repos/kungfu-trader/action-batch-pull-request/actions/workflows/handpick-pull-request.yml/dispatches
              method: "POST"
              headers: '{"X-GitHub-Api-Version": "2022-11-28"}'
              bearer-token: ${{ secrets.GITHUB_PUSH_TOKEN }}
              body: '{"ref": "dev/v1/v1.0", "inputs": {"repo-includes": "${{inputs.repo-includes}}", "repo": "${{inputs.repo}}", "pull-request-title": "${{ github.event.pull_request.title }}"}}'
  