on:
    workflow_call:
      inputs:
        repo-includes:
          type: string
          default: ''
          required: false
        pull-request-title:
          type: string
          required: true
        repo:
          type: string
          default: ''
          required: false
      secrets:
        GITHUB_PUSH_TOKEN:
          required: true

jobs:
    batch-pull-request:
      runs-on: ubuntu-22.04
      steps:
        - name: request
          uses: indiesdev/curl@v1.1
          continue-on-error: true
          with:
                url: https://api.github.com/repos/kungfu-trader/action-batch-pull-request/actions/workflows/handpick-pull-request.yml/dispatches
                method: "POST"
                headers: '{"X-GitHub-Api-Version": "2022-11-28"}'
                bearer-token: ${{ secrets.GITHUB_PUSH_TOKEN }}
                body: '{"ref": "dev/v1/v1.0", "inputs": {"repo-includes": "${{inputs.repo-includes}}", "repo": "${{inputs.repo}}", "pull-request-title": "${{ github.event.pull_request.title }}"}}'
  
        