on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump Version
        id: bump-version
        uses: kungfu-trader/action-bump-version@v3.0-alpha
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          action: "prebuild"

      - name: Docker meta
        id: docker-meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ inputs.image-name }}
          tag-sha: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ inputs.image-name }}:latest, ${{ inputs.image-name }}:${{ steps.bump-version.outputs.version }}, ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}