on:
  workflow_call:
    inputs:
      node-version:
        default: "16"
        type: string
        required: false
      publish-github-npm:
        default: true
        type: boolean
        required: false
      publish-npmjs:
        default: false
        type: boolean
        required: false
      publish-aws-ci:
        default: true
        type: boolean
        required: false
      publish-aws-user:
        default: true
        type: boolean
        required: false
      aws-ci-region:
        default: "us-east-1"
        type: string
        required: false
      aws-user-region:
        default: "cn-northwest-1"
        type: string
        required: false
      bucket-staging-ci:
        default: "kungfu-prebuilt-staging"
        type: string
        required: false
      bucket-staging-user:
        default: "kungfu-prebuilt-staging"
        type: string
        required: false
      bucket-release-ci:
        default: "kungfu-prebuilt"
        type: string
        required: false
      bucket-release-user:
        default: "kungfu-prebuilt"
        type: string
        required: false
      clean-release-ci:
        default: false
        type: boolean
        required: false
      clean-release-user:
        default: false
        type: boolean
        required: false
      cloudfront-id-ci:
        default: ""
        type: string
        required: false
      cloudfront-id-user:
        default: ""
        type: string
        required: false
      cloudfront-paths-ci:
        default: "/*"
        type: string
        required: false
      cloudfront-paths-user:
        default: "/*"
        type: string
        required: false
    secrets:
      GITHUB_PUSH_TOKEN:
        required: true
      NPM_PUSH_TOKEN:
        required: false
      AWS_CI_ACCESS_KEY_ID:
        required: false
      AWS_CI_SECRET_ACCESS_KEY:
        required: false
      AWS_USER_ACCESS_KEY_ID:
        required: false
      AWS_USER_SECRET_ACCESS_KEY:
        required: false
      MONDAY_API_KEY:
        required: false

jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-22.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@kungfu-trader"

      - name: Setup Node.js registry scope
        if: ${{ inputs.publish-github-npm }}
        uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{github.repository_owner}}"

      - name: Bump Version
        uses: kungfu-trader/action-bump-version@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          action: "prebuild"

      - name: Configure AWS Crendentials (CI)
        if: ${{ inputs.publish-aws-ci }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-ci-region }}

      - name: Publish Prebuilt to AWS (CI)
        if: ${{ inputs.publish-aws-ci }}
        uses: kungfu-trader/action-publish-prebuilt@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bucket-staging: ${{ inputs.bucket-staging-ci }}
          bucket-release: ${{ inputs.bucket-release-ci }}
          clean-release: ${{ inputs.clean-release-ci }}
          cloudfront-id: ${{ inputs.cloudfront-id-ci }}
          cloudfront-paths: ${{ inputs.cloudfront-paths-ci }}
          no-comment: 'true'

      - name: Configure AWS Crendentials (User)
        if: ${{ inputs.publish-aws-user }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-user-region }}

      - name: Publish Prebuilt to AWS (User)
        if: ${{ inputs.publish-aws-user }}
        uses: kungfu-trader/action-publish-prebuilt@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bucket-staging: ${{ inputs.bucket-staging-user }}
          bucket-release: ${{ inputs.bucket-release-user }}
          clean-release: ${{ inputs.clean-release-user }}
          cloudfront-id: ${{ inputs.cloudfront-id-user }}
          cloudfront-paths: ${{ inputs.cloudfront-paths-user }}

      - name: Publish New Version To GitHub
        if: ${{ github.event.pull_request.merged && inputs.publish-github-npm }}
        uses: kungfu-trader/action-bump-version@v3
        with:
          token: ${{ secrets.GITHUB_PUSH_TOKEN }}
          action: "postbuild"

      - name: Setup NPM registry
        if: ${{ inputs.publish-npmjs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup NPM registry for owner
        if: ${{ inputs.publish-npmjs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: "@${{github.repository_owner}}"

      - name: Publish to NPM Packages
        if: ${{ inputs.publish-npmjs }}
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUSH_TOKEN }}

      - name: Rollback Check
        if: ${{ failure() }}
        uses: kungfu-trader/action-rollback-release@v1
        with:
          token: ${{ secrets.GITHUB_PUSH_TOKEN }}

      - name: Close Issues 
        if: github.event.pull_request.merged == true
        uses: kungfu-trader/action-merge-close-issue@v1.0-alpha
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          monday_api_key: ${{ secrets.MONDAY_API_KEY }}