name: Release - Verify
on:
  workflow_call:
    secrets:
      KUNGFU_GITHUB_TOKEN:
        required: true
      AWS_US_ACCESS_KEY_ID:
        required: true
      AWS_US_SECRET_ACCESS_KEY:
        required: true
      AWS_CN_ACCESS_KEY_ID:
        required: true
      AWS_CN_SECRET_ACCESS_KEY:
        required: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Version
        uses: kungfu-trader/action-bump-version@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          action: "verify"
