on:
  workflow_call:
    inputs:
      make-docker:
        default: false
        type: boolean
        required: false
      make-package:
        default: true
        type: boolean
        required: false
      node-version:
        default: "14"
        type: string
        required: false
      publish-github-npm:
        default: true
        type: boolean
        required: false
      publish-npmjs:
        default: false
        type: boolean
        required: false
      publish-aws-ci:
        default: true
        type: boolean
        required: false
      publish-aws-user:
        default: true
        type: boolean
        required: false
      aws-ci-region:
        default: "us-east-1"
        type: string
        required: false
      aws-user-region:
        default: "cn-northwest-1"
        type: string
        required: false
      bucket-staging-ci:
        default: "kungfu-prebuilt-staging"
        type: string
        required: false
      bucket-staging-user:
        default: "kungfu-prebuilt-staging"
        type: string
        required: false
      bucket-release-ci:
        default: "kungfu-prebuilt"
        type: string
        required: false
      bucket-release-user:
        default: "kungfu-prebuilt"
        type: string
        required: false
      clean-release-ci:
        default: false
        type: boolean
        required: false
      clean-release-user:
        default: false
        type: boolean
        required: false
      cloudfront-id-ci:
        default: ""
        type: string
        required: false
      cloudfront-id-user:
        default: ""
        type: string
        required: false
      cloudfront-paths-ci:
        default: "/*"
        type: string
        required: false
      cloudfront-paths-user:
        default: "/*"
        type: string
        required: false
    secrets:
      GITHUB_PUSH_TOKEN:
        required: true
      NPM_PUSH_TOKEN:
        required: false
      AWS_CI_ACCESS_KEY_ID:
        required: false
      AWS_CI_SECRET_ACCESS_KEY:
        required: false
      AWS_USER_ACCESS_KEY_ID:
        required: false
      AWS_USER_SECRET_ACCESS_KEY:
        required: false

jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-20.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Make Docker
        if: ${{ inputs.make-docker }}
        uses: ./.github/actions/make-docker
      
      - name: Make Package
        if: ${{ inputs.make-package }}
        uses: ./.github/actions/make-package

      - name: Rollback Check
        if: ${{ failure() }}
        uses: kungfu-trader/action-rollback-release@v1.0-alpha
        with:
          token: ${{ secrets.GITHUB_PUSH_TOKEN }}
