on:
  workflow_call:
    inputs:
      prebuild:
        default: true
        type: boolean
        required: false
      node-version:
        default: "16"
        type: string
        required: false
      builder-container:
        default: "docker.io/kungfutrader/kungfu-builder-ubuntu:v1.0.0"
        type: string
        required: false
      enable-linux:
        default: true
        type: boolean
        required: false
      enable-macos:
        default: true
        type: boolean
        required: false
      enable-windows:
        default: true
        type: boolean
        required: false
      build-runner-linux-labels:
        default: ""
        type: string
        required: false
      publish-versioning:
        default: true
        type: boolean
        required: false
      publish-aws-ci:
        default: true
        type: boolean
        required: false
      publish-aws-user:
        default: true
        type: boolean
        required: false
      action-bump-version-repository:
        default: "kungfu-systems/action-bump-version"
        type: string
        required: false
      action-bump-version-ref:
        default: "v3"
        type: string
        required: false
    secrets:
      NODE_AUTH_TOKEN:
        required: false

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  prepare:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Bump Version Action
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.action-bump-version-repository }}
          ref: ${{ inputs.action-bump-version-ref }}
          path: node_modules/.github-actions/action-bump-version
          persist-credentials: false

      - name: Verify Version
        if: ${{ github.event_name == 'pull_request' }}
        run: node node_modules/.github-actions/action-bump-version/dist/index.js
        env:
          KUNGFU_ACTION_BUMP_VERSION_ALLOW_LOCAL: "true"
          INPUT_TOKEN: ${{ github.token }}
          INPUT_ACTION: "verify"
