on:
  workflow_call:
    inputs:
      aws-role-arn:
        default: "arn:aws-cn:iam::186931371703:role/github-actions-role-dev"
        type: string
        required: false
      aws-region:
        default: "cn-northwest-1"
        type: string
        required: false
      bucket-release:
        default: "kungfu-releases"
        type: string
        required: false
      cloudfront-id:
        default: "E1GP1ZMAI7TELG"
        type: string
        required: false
      release-path:
        default: "static"
        type: string
        required: false
      product:
        type: string
        required: true
      lower-edge:
        type: string
        required: false
      upper-edge:
        type: string
        required: false
      base-id:
        type: string
        required: false
        default: "appAdi5zFFEsCzmEM"
      release-url:
        type: string
        default: 'https://releases.kungfu-trader.com'
        required: false
      exclude:
        type: string
        required: false
      product-name: 
        type: string
        required: false
      repo: 
        type: string
        required: false
    secrets:
      AIRTABLE_API_KEY:
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  sync-release-page:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Crendentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role-arn }}
          role-session-name: github-dev
          aws-region: ${{ inputs.aws-region }}

      - name: Generate Download Page
        if: ${{ github.event.pull_request.merged }}
        uses: kungfu-trader/action-generate-download-page@dev/v1/v1.0
        with:
          apiKey: ${{ secrets.AIRTABLE_API_KEY }}
          bucket-release: ${{ inputs.bucket-release }}
          airtable-baseid: ${{ inputs.base-id }}

      - name: Generate Release Page
        uses: kungfu-trader/action-generate-release-page@dev/v1/v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          apiKey: ${{ secrets.AIRTABLE_API_KEY }}
          product: ${{ inputs.product }}
          repo: ${{ inputs.repo }}
          product-name: ${{ inputs.product-name }}
          release-path: ${{ inputs.release-path }}
          release-url: ${{ inputs.release-url }}
          lower-edge: ${{ inputs.lower-edge }}
          upper-edge: ${{ inputs.upper-edge }}
          exclude: ${{ inputs.exclude }}
          base-id: ${{ inputs.base-id }}
          bucket-release: ${{ inputs.bucket-release }}

      - name: Publish Release Page to AWS
        uses: kungfu-trader/action-publish-prebuilt@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-path: "dist"
          bucket-release: ${{ inputs.bucket-release }}
          clean-release: false
          cloudfront-id: ${{ inputs.cloudfront-id }}
          cloudfront-paths: /${{ inputs.release-path }}/*
