on:
  workflow_call:
    inputs:
      remote-host:
        default: "git-codecommit.cn-northwest-1.amazonaws.com.cn"
        type: string
        required: false
      remote-path:
        default: "v1/repos"
        type: string
        required: false
      remote-repo:
        default: ""
        type: string
        required: true
      force:
        default: false
        type: boolean
        required: false
    secrets:
      REMOTE_USER:
        required: false
      REMOTE_CREDENTIAL:
        # format: https://username:password@host
        # run git locally with credential.helper=store and check ~/.git-credentials to get the value
        required: false

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Remote Git Repo
        run: |
          echo ${{secrets.REMOTE_CREDENTIAL}} >> ~/.git-credentials
          git config --global credential.https://${{inputs.remote-host}}.helper store
          git config --global credential.https://${{inputs.remote-host}}.username ${{ secrets.REMOTE_USER }}
          git remote add peer "https://${{inputs.remote-host}}/${{inputs.remote-path}}/${{inputs.remote-repo}}"
          git fetch peer
      
      - name: Push Remote Git Repo
        if: ${{ !inputs.force }}
        run: git push peer ${{ github.ref_name }}
      
      - name: Push Remote Git Repo (Force)
        if: ${{ inputs.force }}
        run: git push --force peer ${{ github.ref_name }}
