on:
    workflow_call:
      inputs:
        node-version:
            default: "16"
            type: string
            required: false
        aws-user-region:
            default: "cn-northwest-1"
            type: string
            required: false
        bucket-staging-user:
            default: "kungfu-prebuilt-staging"
            type: string
            required: false
        preview-files:
            default: ".*"
            type: string
            required: false
        max-preview-links:
            default: "32"
            type: string
            required: false
      secrets:
        NODE_AUTH_TOKEN:
          required: false
        AWS_USER_ACCESS_KEY_ID:
            required: false
        AWS_USER_SECRET_ACCESS_KEY:
            required: false
    
jobs:
    prepare:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set Pull Request Title
          uses: kungfu-trader/action-bump-version@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            action: "verify"

        - name: Set Collaborators
          uses: kungfu-trader/action-set-collaborators@v1
          with:
            token: ${{ secrets.NODE_AUTH_TOKEN }}
            manager: kungfu-developers

    build:
        name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        needs: prepare
        strategy:
            matrix:
                os: [macos-12]
                python-version: ['3.10']
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}            
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Setup Node.js environment
            uses: actions/setup-node@v3
            with:
              node-version: ${{ inputs.node-version }}
              registry-url: "https://npm.pkg.github.com"
              scope: "@kungfu-trader"
    
          - name: Setup Node.js registry scope
            uses: actions/setup-node@v3
            with:
              registry-url: "https://npm.pkg.github.com"
              scope: "@${{github.repository_owner}}"

          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python-version }}

          - name: Install Pipenv
            run: |
                  pipx install pipenv==2023.9.1
                  pipx install poetry==1.6.1

          - name: Bump Version
            uses: kungfu-trader/action-bump-version@v3
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
                action: "prebuild"

          - name: Install pip dependencies
            run: |
                pipenv install

          - name: Setup Build Environment
            uses: nick-fields/retry@v2
            with:
                  timeout_minutes: 10
                  max_attempts: 3
                  command: yarn --network-timeout=1000000 install --frozen-lockfile
                  new_command_on_retry: yarn --network-timeout=5000000 install --frozen-lockfile

          - name: Run yarn build
            run: yarn build
            env: 
                PYTHON_VERSION: ${{ matrix.python-version }}
        
          - name: Upload Prebuilt (without versions)
            uses: actions/upload-artifact@v3
            with:
                name: "Prebuilt-${{matrix.os}}-${{matrix.python-version}}-${{github.actor}}-${{github.sha}}"
                path: |
                    **/build/**/*.*
                    **/build/**/**/*.*

    verify:
      if: ${{ always() }}
      needs: [prepare, build]
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Bump Version
          uses: kungfu-trader/action-bump-version@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            action: "prebuild"
        
        - name: Configure AWS Crendentials (User)
          uses: aws-actions/configure-aws-credentials@v1-node16
          with:
              aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
              aws-region: ${{ inputs.aws-user-region }}
        
        - name: Publish Prebuilt to AWS (User)
          uses: kungfu-trader/action-publish-prebuilt@v2
          with:
              token: ${{ secrets.GITHUB_TOKEN }}
              artifacts-path: "github-artifacts"
              bucket-staging: ${{ inputs.bucket-staging-user }}
              preview-files: ${{ inputs.preview-files }}
              max-preview-links: ${{ inputs.max-preview-links }}
  
        - name: Verify Version
          uses: kungfu-trader/action-bump-version@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            action: "verify"
  