name: Release - Verify

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

jobs:
  try:
    uses: ./.github/workflows/.release-verify.yml
    with:
      prebuild: false
      check-format: false
      list-dependencies: true
  
  verify:
    # report status for branch protection rule
    needs: try
    runs-on: ubuntu-20.04
    steps:
      - name: report
        run: echo verified
