name: Release - Verify

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

jobs:
  verify:
    uses: ./.github/workflows/.release-verify.yml
    with:
      prebuild: true
