name: Release - Verify

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

jobs:
  try:
    uses: ./.github/workflows/.release-verify.yml
    with:
      prebuild: false
  
  verify:
    # report status for branch protection rule
    needs: try
