name: Release - Verify

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

jobs:
  try:
    uses: ./.github/workflows/.release-verify.yml
    with:
      prebuild: false
      check-format: false
      find-dependencies: true
    secrets:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      NODE_AUTH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
  
  verify:
    # report status for branch protection rule
    needs: try
    runs-on: ubuntu-20.04
    steps:
      - name: report
        run: echo verified
