name: Release - New Version

on:
  pull_request:
    types: [closed]
    branches:
      - alpha/v*/v*
      - release/v*/v*

jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/.release-new-version.yml
    secrets:
      KUNGFU_GITHUB_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
