name: Schedule - Clean Up GitHub Storage
on:
  push:
  schedule:
    - cron: '0 12 * * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 14days
