name: Schedule - Sync GitHub Messages to Airtable
on:
  schedule:
    - cron: '30 11,17 * * *'

jobs:
  traversal-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: kungfu-trader/action-sync-airtable@v2
        with:
          token: ${{ secrets.KUNGFU_GITHUB_TOKEN }}