name: Schedule - Purge GitHub Artifacts
on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kungfu-trader/action-purge-artifacts@v1
        with:
          token: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
          expire-in: 14days
