name: Schedule - Sync GitHub Pull Request to Airtable
on:
  watch:
    types: [started]
  schedule:
    - cron: '0 9 * * *'

jobs:
  full-sync-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: kungfu-trader/action-sync-pr@v1.0-alpha
        with:
          token: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
          apiKey: ${{ secrets.AIRTABLE_API_KEY }}
          base: ${{ secrets.AIRTABLE_BASE_ID }}